### PR TITLE
Fix hardcoded hook names in the WorkflowsList controller

### LINKED ISSUE #1289: Fix hardcoded hook names in the WorkflowsList controller
Define or use constants in the HooksAbstract class.

https://github.com/publishpress/PublishPress-Future/blob/e294d310f5865a6af628fbc144986217ce3285bb/src/Modules/Workflows/Controllers/WorkflowsList.php#L102-L112

### PR DESCRIPTION
**Pull request by ojopaul**
This PR updated the hardcoded hook names in the WorkflowsList controller to fix #1289

### CODE REVIEW

File: src/Modules/Workflows/Controllers/WorkflowsList.php [hunk 1]
```diff
@@ -73,7 +73,7 @@ public function initialize()
         );
 
         $this->hooks->addAction(
-            "post_row_actions",
+            HooksAbstract::FILTER_POST_ROW_ACTIONS,
```
Comment (andergmartins) [inline src/Modules/Workflows/Controllers/WorkflowsList.php:76]: @ojopaul this is an "action", but was named as "filter"

File: src/Modules/Workflows/Controllers/WorkflowsList.php [hunk 2]
```diff
@@ -99,14 +99,14 @@ public function initialize()
         );
 
         $this->hooks->addAction(
-            'the_title',
+            HooksAbstract::FILTER_THE_TITLE,
```
Comment (andergmartins) [inline src/Modules/Workflows/Controllers/WorkflowsList.php:102]: @ojopaul this is an "action", but was named as "filter"

**Review by andergmartins — CHANGES_REQUESTED** [review]

File: src/Modules/Workflows/Controllers/WorkflowsList.php (hunk 1 above)
Comment (andergmartins) [reply src/Modules/Workflows/Controllers/WorkflowsList.php:76]: Just correcting my comment, the issue is actualy in the line before. It should be `$this->hooks->addFilter`.

File: src/Modules/Workflows/Controllers/WorkflowsList.php (hunk 2 above)
Comment (andergmartins) [reply src/Modules/Workflows/Controllers/WorkflowsList.php:102]: Just correcting my comment, the issue is actually in the line before. It should be `$this->hooks->addFilter`.

**Review by andergmartins — APPROVED** [review]
